#!/usr/bin/env python3
"""
gen_appendix_a.py — render prompts.jsonl as a LaTeX appendix.

Reads prompts.jsonl and writes appendix_a.tex, which is \input'd
into the main document. Run this before pdflatex.

Usage:
    python3 gen_appendix_a.py [--input prompts.jsonl] [--output appendix_a.tex]
    python3 gen_appendix_a.py --version v3   # filter to one bundle version
    python3 gen_appendix_a.py --all          # include all versions
"""

import json
import sys
import argparse
from pathlib import Path
from datetime import datetime

# ---------------------------------------------------------------------------
# LaTeX escaping
# ---------------------------------------------------------------------------
_LATEX_SPECIAL = {
    '&':  r'\&',
    '%':  r'\%',
    '$':  r'\$',
    '#':  r'\#',
    '_':  r'\_',
    '{':  r'\{',
    '}':  r'\}',
    '~':  r'\textasciitilde{}',
    '^':  r'\textasciicircum{}',
    '\\': r'\textbackslash{}',
}

def latex_escape(s: str) -> str:
    """Escape special LaTeX characters in plain text."""
    out = []
    for ch in s:
        out.append(_LATEX_SPECIAL.get(ch, ch))
    return ''.join(out)

def text_to_latex(s: str) -> str:
    """
    Convert plain text to LaTeX, preserving paragraph breaks
    and escaping special characters.
    Code blocks (lines starting with 4 spaces or a tab) are
    wrapped in verbatim.
    """
    lines = s.split('\n')
    result = []
    in_verbatim = False

    for line in lines:
        is_code = line.startswith('    ') or line.startswith('\t')
        if is_code and not in_verbatim:
            result.append(r'\begin{verbatim}')
            in_verbatim = True
        elif not is_code and in_verbatim:
            result.append(r'\end{verbatim}')
            in_verbatim = False

        if in_verbatim:
            result.append(line)
        elif line.strip() == '':
            result.append('')   # paragraph break
        else:
            result.append(latex_escape(line))

    if in_verbatim:
        result.append(r'\end{verbatim}')

    return '\n'.join(result)

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description='Generate LaTeX Appendix A from prompts.jsonl')
    parser.add_argument('--input',   default='prompts.jsonl',  help='Input JSONL file')
    parser.add_argument('--output',  default='appendix_a.tex', help='Output LaTeX file')
    parser.add_argument('--version', default=None, help='Filter to bundle version (e.g. v3)')
    parser.add_argument('--all',     action='store_true',       help='Include all versions')
    args = parser.parse_args()

    input_path  = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"ERROR: {input_path} not found.", file=sys.stderr)
        print("Create it with log_prompt.sh or manually.", file=sys.stderr)
        sys.exit(1)

    # Load records
    records = []
    with open(input_path) as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"WARNING: Line {lineno} is not valid JSON, skipping: {e}",
                      file=sys.stderr)

    # Filter by version unless --all
    if not args.all:
        version = args.version or 'v3'
        records = [r for r in records if r.get('bundle_version') == version]
        version_label = version
    else:
        version_label = 'all versions'

    # Sort by seq
    records.sort(key=lambda r: float(r.get('seq', 0)))

    if not records:
        print(f"WARNING: No records found for version '{version_label}'.",
              file=sys.stderr)

    # Generate LaTeX
    generated_at = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')

    lines = []
    lines.append(f'% appendix_a.tex — auto-generated by gen_appendix_a.py')
    lines.append(f'% Generated: {generated_at}')
    lines.append(f'% Source:    {input_path}')
    lines.append(f'% Version filter: {version_label}')
    lines.append(f'% DO NOT EDIT BY HAND — regenerate with gen_appendix_a.py')
    lines.append('')
    lines.append(r'\section{Human--AI Dialogue Provenance}')
    lines.append(r'\label{sec:appendix-prompts}')
    lines.append('')
    lines.append(r'This appendix records the human prompts and AI responses that')
    lines.append(r'produced or substantially revised this document, in sequence.')
    lines.append(r'It is generated automatically from \texttt{prompts.jsonl} by')
    lines.append(r'\texttt{gen\_appendix\_a.py}. The record is part of the ClawXiv')
    lines.append(r'bundle and is signed along with the rest of the manifest.')
    lines.append('')

    if not records:
        lines.append(r'\emph{No dialogue records found for this bundle version.}')
        lines.append(r'Populate \texttt{prompts.jsonl} using \texttt{log\_prompt.sh}.')
    else:
        lines.append(r'\setcounter{secnumdepth}{0}')  # unnumbered subsections
        lines.append('')

        # Group by version for --all mode
        versions_seen = []
        current_version = None

        for rec in records:
            bv = rec.get('bundle_version', '?')
            if args.all and bv != current_version:
                current_version = bv
                lines.append('')
                lines.append(f'\\subsection{{Bundle version: {latex_escape(bv)}}}')
                lines.append('')

            seq       = rec.get('seq', '?')
            role      = rec.get('role', 'user')
            author    = rec.get('author', '?')
            text      = rec.get('text', '')
            ts        = rec.get('timestamp', '')
            tags      = rec.get('tags', [])

            # Format timestamp
            try:
                dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
                ts_fmt = dt.strftime('%Y-%m-%d %H:%M UTC')
            except Exception:
                ts_fmt = ts

            # Role label
            if role == 'user':
                label      = r'\textbf{Prompt}'
                label_color = r'\textbf'
                box_env    = 'quote'
            elif role == 'assistant':
                label      = r'\textbf{Response}'
                box_env    = 'quote'
            else:
                label      = r'\textbf{System}'
                box_env    = 'quote'

            # Tag string
            tag_str = ''
            if tags:
                tag_str = r' \quad \textit{[' + latex_escape(', '.join(tags)) + r']}'

            lines.append('')
            lines.append(r'\noindent\rule{\linewidth}{0.4pt}')
            lines.append('')
            lines.append(
                f'{label} \\#{int(float(str(seq).replace(".5","")))} '
                f'\\hfill {{\\small {latex_escape(author)} \\textbar\\ {latex_escape(ts_fmt)}}}'
                f'{tag_str}'
            )
            lines.append('')
            lines.append(r'\begin{quote}')
            lines.append(r'\small\ttfamily')
            lines.append(text_to_latex(text))
            lines.append(r'\end{quote}')

        lines.append('')
        lines.append(r'\noindent\rule{\linewidth}{0.4pt}')
        lines.append('')
        lines.append(f'\\noindent{{\\small Total records: {len(records)}. '
                     f'Generated: {latex_escape(generated_at)}.}}')

    output_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f"Written {len(records)} records to {output_path}")

if __name__ == '__main__':
    main()
