#!/usr/bin/env bash
# publish.sh — build, sign, pin, and publish a ClawXiv bundle
#
# Usage:
#   ./publish.sh [--skip-compile] [--skip-ipfs] [--skip-github]
#
# Prerequisites:
#   - gpg with keys generated by keygen.sh
#   - ipfs (Kubo) daemon running, OR ipfs CLI pointing to a remote API
#   - gh (GitHub CLI) authenticated, OR git with push access to origin
#   - pdflatex (TeX Live 2023 or later)
#
# Environment variables (set these in your shell or a .env file that
# is NOT committed to the repository):
#   AK_EMAIL        GPG email for A. Kornai key  (default: andras@kornai.com)
#   AI_EMAIL        GPG email for AI key          (default: claude-sonnet-4-6@clawxiv.operator.kornai.com)
#   IPNS_KEY        IPFS key name for IPNS update (default: clawxiv)
#   GITHUB_REPO     GitHub repo slug              (default: kornai/clawxiv)
#
# What this script does:
#   1. Compile LaTeX (2 passes)
#   2. Compute SHA-256 hashes of source + PDF
#   3. Update manifest.json with current hashes and timestamp
#   4. Sign manifest with both keys (detached .sig files)
#   5. Add bundle to IPFS, record CID
#   6. Update IPNS record to new CID
#   7. Commit and push to GitHub

set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "$0")" && pwd)"
TEX_FILE="clawxiv_whitepaper_v2.tex"
PDF_FILE="clawxiv_whitepaper_v2.pdf"
MANIFEST="manifest.json"
KEYS_DIR="${BUNDLE_DIR}/keys"

AK_EMAIL="${AK_EMAIL:-andras@kornai.com}"
AI_EMAIL="${AI_EMAIL:-claude-sonnet-4-6@clawxiv.operator.kornai.com}"
IPNS_KEY="${IPNS_KEY:-clawxiv}"
GITHUB_REPO="${GITHUB_REPO:-kornai/clawxiv}"

SKIP_COMPILE=false
SKIP_IPFS=false
SKIP_GITHUB=false

for arg in "$@"; do
  case "$arg" in
    --skip-compile) SKIP_COMPILE=true ;;
    --skip-ipfs)    SKIP_IPFS=true ;;
    --skip-github)  SKIP_GITHUB=true ;;
  esac
done

cd "$BUNDLE_DIR"

# -----------------------------------------------------------------------
echo "[1/7] Checking prerequisites..."

check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo "  MISSING: $1 — $2"
    MISSING=1
  else
    echo "  OK: $1"
  fi
}

MISSING=0
check_cmd gpg      "required for signing"
check_cmd sha256sum "required for hashing (macOS: use 'shasum -a 256')"
check_cmd python3  "required for manifest update"
$SKIP_COMPILE || check_cmd pdflatex "required for compilation (--skip-compile to skip)"
$SKIP_IPFS    || check_cmd ipfs     "required for IPFS pinning (--skip-ipfs to skip)"
$SKIP_GITHUB  || check_cmd git      "required for GitHub push (--skip-github to skip)"

if [[ $MISSING -ne 0 ]]; then
  echo ""
  echo "ERROR: Missing prerequisites. Install them or use --skip-* flags."
  exit 1
fi

# macOS sha256sum compatibility
SHA256="sha256sum"
if ! command -v sha256sum &>/dev/null && command -v shasum &>/dev/null; then
  SHA256="shasum -a 256"
fi

# -----------------------------------------------------------------------
if ! $SKIP_COMPILE; then
  echo ""
  echo "[2/7] Generating Appendix A from prompts.jsonl..."
  if [[ -f "${BUNDLE_DIR}/prompts.jsonl" ]]; then
    python3 "${BUNDLE_DIR}/gen_appendix_a.py" \
      --input  "${BUNDLE_DIR}/prompts.jsonl" \
      --output "${BUNDLE_DIR}/appendix_a.tex" \
      --version "${BUNDLE_VERSION:-v2}"
    echo "      appendix_a.tex generated."
  else
    echo "      prompts.jsonl not found — creating empty appendix_a.tex"
    echo "% appendix_a.tex — empty (no prompts logged yet)" \
      > "${BUNDLE_DIR}/appendix_a.tex"
    echo "\\\\section{Human--AI Dialogue Provenance}" \
      >> "${BUNDLE_DIR}/appendix_a.tex"
    echo "\\\\emph{No dialogue records found. Populate prompts.jsonl using log\\_prompt.sh.}" \
      >> "${BUNDLE_DIR}/appendix_a.tex"
  fi

  echo ""
  echo "      Compiling LaTeX (pass 1)..."
  pdflatex -interaction=nonstopmode "$TEX_FILE" > /tmp/clawxiv_latex1.log 2>&1
  echo "      Pass 1 done."

  echo "      Compiling LaTeX (pass 2)..."
  pdflatex -interaction=nonstopmode "$TEX_FILE" > /tmp/clawxiv_latex2.log 2>&1
  echo "      Pass 2 done. PDF: $PDF_FILE"
else
  echo ""
  echo "[2/7] Skipping compilation (--skip-compile)."
  [[ -f "$PDF_FILE" ]] || { echo "ERROR: $PDF_FILE not found. Cannot skip compile."; exit 1; }
fi

# -----------------------------------------------------------------------
echo ""
echo "[3/7] Computing SHA-256 hashes..."

HASH_TEX=$(${SHA256} "$TEX_FILE" | awk '{print $1}')
HASH_PDF=$(${SHA256} "$PDF_FILE" | awk '{print $1}')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "      $TEX_FILE : $HASH_TEX"
echo "      $PDF_FILE : $HASH_PDF"

# -----------------------------------------------------------------------
echo ""
echo "[4/7] Updating manifest.json..."

python3 - <<PYEOF
import json, sys

with open("${MANIFEST}") as f:
    m = json.load(f)

m["created_at"] = "${TIMESTAMP}"

for entry in m["files"]:
    if entry["path"] == "${TEX_FILE}":
        entry["hash_sha256"] = "${HASH_TEX}"
    elif entry["path"] == "${PDF_FILE}":
        entry["hash_sha256"] = "${HASH_PDF}"

with open("${MANIFEST}", "w") as f:
    json.dump(m, f, indent=2, ensure_ascii=False)
    f.write("\n")

print("      manifest.json updated.")
PYEOF

# -----------------------------------------------------------------------
echo ""
echo "[5/7] Signing manifest with both keys..."

# Sign with AK key
gpg --armor --detach-sign \
    --local-user "$AK_EMAIL" \
    --output "${MANIFEST}.ak.sig" \
    "$MANIFEST"
echo "      Signed with AK key -> ${MANIFEST}.ak.sig"

# Sign with operator-held AI contributor key
gpg --armor --detach-sign \
    --local-user "$AI_EMAIL" \
    --output "${MANIFEST}.ai.sig" \
    "$MANIFEST"
echo "      Signed with AI contributor key -> ${MANIFEST}.ai.sig"

echo ""
echo "      To verify later:"
echo "        gpg --verify ${MANIFEST}.ak.sig ${MANIFEST}"
echo "        gpg --verify ${MANIFEST}.ai.sig ${MANIFEST}"

# -----------------------------------------------------------------------
if ! $SKIP_IPFS; then
  echo ""
  echo "[6/7] Adding bundle to IPFS..."

  # Add the entire bundle directory as a DAG
  CID=$(ipfs add -r --quieter --cid-version 1 .)
  echo "      Bundle CID: $CID"

  # Update IPNS record
  echo "      Updating IPNS key '$IPNS_KEY' -> $CID ..."
  ipfs name publish --key="$IPNS_KEY" "/ipfs/$CID"
  echo "      IPNS updated."
  echo ""
  echo "      Access via:"
  echo "        ipfs cat /ipns/$(ipfs key list -l | grep $IPNS_KEY | awk '{print $1}')"
  echo "        https://ipfs.io/ipfs/$CID"

  # Record CID in a local file for reference
  echo "$CID  $TIMESTAMP" >> cid_history.txt
  echo "      CID recorded in cid_history.txt"
else
  echo ""
  echo "[6/7] Skipping IPFS (--skip-ipfs)."
fi

# -----------------------------------------------------------------------
if ! $SKIP_GITHUB; then
  echo ""
  echo "[7/7] Committing and pushing to GitHub..."

  git add \
    "$TEX_FILE" \
    "$PDF_FILE" \
    "$MANIFEST" \
    "${MANIFEST}.ak.sig" \
    "${MANIFEST}.ai.sig" \
    "${KEYS_DIR}/ak_pubkey.asc" \
    "${KEYS_DIR}/claude_pubkey.asc" \
    keygen.sh \
    publish.sh \
    .gitignore

  # Add cid_history if IPFS step ran
  $SKIP_IPFS || git add cid_history.txt 2>/dev/null || true

  COMMIT_MSG="ClawXiv whitepaper v2 (${TIMESTAMP})

  - Scaling claims reworded to architectural capability
  - Economics: social vouching model, storage sustainability separated
  - Governance: honest about zero current legal capacity
  - AI authorship: grounded in Gewirth/PPA framework
  - Co-authored by Claude Sonnet 4.6 (Anthropic)
  "

  git commit -m "$COMMIT_MSG"
  git push origin main
  echo "      Pushed to github.com/${GITHUB_REPO}"
else
  echo ""
  echo "[7/7] Skipping GitHub push (--skip-github)."
fi

# -----------------------------------------------------------------------
echo ""
echo "=== Publish complete ==="
echo ""
echo "Bundle files:"
echo "  $TEX_FILE        (source)"
echo "  $PDF_FILE        (compiled artifact)"
echo "  $MANIFEST              (canonical manifest)"
echo "  ${MANIFEST}.ak.sig     (AK signature)"
echo "  ${MANIFEST}.ai.sig     (AI contributor signature)"
echo "  ${KEYS_DIR}/ak_pubkey.asc"
echo "  ${KEYS_DIR}/claude_pubkey.asc"
echo ""
echo "Remember to update the IPNS address in the paper's appendix"
echo "if this is the first publish with a new IPNS key."
